# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.srcs/sources_1/ip/VTC/VTC.xci
# IP: The module: 'VTC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/VTC/VTC_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'VTC'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/VTC/VTC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VTC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.srcs/sources_1/ip/VTC/VTC.xci
# IP: The module: 'VTC' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/VTC/VTC_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'VTC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/VTC/VTC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VTC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
