# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/ip/ip_0/bd_5fd0_v_hdmi_tx_0_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_5fd0_v_hdmi_tx_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/ip/ip_0/bd_5fd0_v_hdmi_tx_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_5fd0_v_hdmi_tx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/ip/ip_0/bd_5fd0_v_hdmi_tx_0_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_5fd0_v_hdmi_tx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/ip/ip_0/bd_5fd0_v_hdmi_tx_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_5fd0_v_hdmi_tx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
