@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Thu Oct 19 16:05:22 -0400 2023
=======
REM Generated by Vivado on Thu Oct 12 14:23:39 -0400 2023
>>>>>>> 9c971ac2998e47faaabea0845235ccde257fe477
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
<<<<<<< HEAD
echo "xsim tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -view H:/Senior-Project-2023/SENIOR_PROJECT/DIGLENT_BLOCK/tb_behav.wcfg -log simulate.log"
call xsim  tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -view H:/Senior-Project-2023/SENIOR_PROJECT/DIGLENT_BLOCK/tb_behav.wcfg -log simulate.log
=======
echo "xsim tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -log simulate.log"
call xsim  tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -log simulate.log
>>>>>>> 9c971ac2998e47faaabea0845235ccde257fe477
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
