# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.srcs/sources_1/ip/HDMI_transmitter/HDMI_transmitter.xci
# IP: The module: 'HDMI_transmitter' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/bd_5fd0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5fd0 || ORIG_REF_NAME==bd_5fd0} -quiet] -quiet

# IP: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/ip/ip_0/bd_5fd0_v_hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5fd0_v_hdmi_tx_0 || ORIG_REF_NAME==bd_5fd0_v_hdmi_tx_0} -quiet] -quiet

# IP: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/ip/ip_1/bd_5fd0_const_0_1bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5fd0_const_0_1bit_0 || ORIG_REF_NAME==bd_5fd0_const_0_1bit_0} -quiet] -quiet

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/bd_5fd0_ooc.xdc

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/HDMI_transmitter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_transmitter'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.srcs/sources_1/ip/HDMI_transmitter/HDMI_transmitter.xci
# IP: The module: 'HDMI_transmitter' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/bd_5fd0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5fd0 || ORIG_REF_NAME==bd_5fd0} -quiet] -quiet

# IP: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/ip/ip_0/bd_5fd0_v_hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5fd0_v_hdmi_tx_0 || ORIG_REF_NAME==bd_5fd0_v_hdmi_tx_0} -quiet] -quiet

# IP: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/ip/ip_1/bd_5fd0_const_0_1bit_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5fd0_const_0_1bit_0 || ORIG_REF_NAME==bd_5fd0_const_0_1bit_0} -quiet] -quiet

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/bd_0/bd_5fd0_ooc.xdc

# XDC: h:/Users/leopole1/HDMI IP TEST/HDMI IP TEST.gen/sources_1/ip/HDMI_transmitter/HDMI_transmitter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HDMI_transmitter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
