# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/Senior-Project-2023/SENIOR_PROJECT/New_Vram/New_Vram.srcs/sources_1/ip/v_tc_0_1/v_tc_0.xci
# IP: The module: 'v_tc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Senior-Project-2023/SENIOR_PROJECT/New_Vram/New_Vram.gen/sources_1/ip/v_tc_0_1/v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/Senior-Project-2023/SENIOR_PROJECT/New_Vram/New_Vram.gen/sources_1/ip/v_tc_0_1/v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: h:/Senior-Project-2023/SENIOR_PROJECT/New_Vram/New_Vram.srcs/sources_1/ip/v_tc_0_1/v_tc_0.xci
# IP: The module: 'v_tc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/Senior-Project-2023/SENIOR_PROJECT/New_Vram/New_Vram.gen/sources_1/ip/v_tc_0_1/v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: h:/Senior-Project-2023/SENIOR_PROJECT/New_Vram/New_Vram.gen/sources_1/ip/v_tc_0_1/v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
